<?php

namespace Tests\Unit;

use App\Http\Controllers\MessagesController;
use App\Repositories\MessagesRepository;;

use Illuminate\Http\Request;
use Mockery;
use PHPUnit\Framework\TestCase;

class MessagesControllerTest extends TestCase
{
    protected function tearDown(): void
    {
        Mockery::close();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic feature test example.
     */
    public function test_example(): void
    {
        $mockery = new Mockery();
        $messagesRepository = $mockery->mock(MessagesRepository::class);
        $messagesController = new MessagesController($messagesRepository);
        $messagesRepository->shouldR0eceive('getMessages')->once();
        $request = new Request();
        $request->replace(['sorted' => 'DESC']);
        $messagesController->index($request);
    }
}
